### ISSUE TITLE
EL2: No video output

### ISSUE THREAD

**Issue by CoiaPrant233** [jglathe/linux_ms_dev_kit#12]
```
root@wdk2023:~# cat /etc/armbian-grub-with-dtb 
BOOT_FDT_FILE="qcom/sc8280xp-microsoft-dev-kit-2023.dtb"
```

Armbian using `sc8280xp-microsoft-dev-kit-2023.dtb` as dtb file name, modify it then u can compile kernel to deb and use apt install it directly

**Comment by jglathe** [comment]
The branch jg/el2-iommu-v6.8 is the ongoing effort to get the box up as good as possible on EL2 when booting with the help of [@travmurav 's slbounce](https://github.com/TravMurav/slbounce). The key changes by now are:
- no ZAP shader node in the dts
- arm-smmuv3 enabled as pcie_smmu with mappings
- hack in drivers/iommu/iommu.c to allow the use of iommu despite multiple iommu drivers being loaded.

With that the WDK boots up with PCIe operational, and you get video output on display port. The sc8280xp specific firmware files are not loaded, so it is not full support with ZAP shader and Venus, but quite usable nonetheless.
The use of multiple IOMMU drivers is quite new, it starts to come to mainline with 6.8 as it seems. Therefore not everything works (yet) or is intentionally disabled.
The use should be straight forward compile and install with devkit_defconfig as described in [master/README.md](https://github.com/jglathe/linux_ms_dev_kit/blob/master/README.md). With armbian the way may be different, might be adapted a little. 
I have not yet tried to boot to EL2 from internal nvme SSD.

**Comment by jglathe** [comment]
dtbhack is not needed to boot this, btw. I just use EFI shell -> load slbounce.efi -> exit -> grub to the right menu.

**Comment by jglathe** [comment]
Did you get the display to work, though? Attached my dmesg for reference.
[el2_dmesg.txt](https://github.com/jglathe/linux_ms_dev_kit/files/14420554/el2_dmesg.txt)

**Comment by jglathe** [comment]
This is my cmdline for the kernel: `pd_ignore_unused clk_ignore_unused regulator_ignore_unused arm64.nopauth efi=noruntime drm.debug=0x100 "dyndbg=file drivers/regulator/core.c +p;file drivers/base/firmware_loader/main.c +fmp"`

**Comment by jglathe** [comment]
Hmm I assume you’re using the display port? Does it work when you boot to EL1?Von meinem iPhone gesendetAm 02.03.2024 um 13:58 schrieb CoiaPrant ***@***.***>:﻿
Not working
dmesg

**Comment by jglathe** [comment]
I'm using DP normally, no adapter. I have a miniDP to DVI adapter, too, working great (needs to be an active version). TypeC won't work on EL2 (it does - well enough - on EL1) because the coprocessors are needed for the USB multiplexing.
What I've seen is that you still get the WARNs. I tweaked the dts a little since then, I don't get WARNs anymore. It should work even without the [hack in iommu.c](https://github.com/jglathe/linux_ms_dev_kit/commit/89d34b1e73a7a2c72e61b11b080e9b7b1c975d57) now. Maybe rebuild with the updated branch? OTOH I would recommend to load the newest Volterra-specific firmwares from Windows with [this script](https://github.com/jglathe/wdk2023_fw_fetch). Armbian-firmware is not the newest IMO.

**Comment by jglathe** [comment]
Thanks for the hint. I've seen these messages too, they are correctable errors due to PCIe L0s ASPM state. It is already solved for the X13s, need to update the WDK dts accordingly. Great that video is working. I will open a new issue for the AER messages.

**Comment by jglathe** [comment]
No, gpu is integrated and not on the PCIe bus. This sounds a little odd, can you post the dmesg?

**Comment by jglathe** [comment]
Oh, that... :smirk: These are the coprocessors that rely on the HYP firmware to boot... actually this firmware is no longer there after slbounce. Linux is booting on EL2 where HYP was. Of what I heard there are other ways to boot these processors, but this needs to be changed in the kernel (if we can find out how). For all the parts relying on HYP firmware solutions need to be found:

- ZAP Shader
- Venus firmware
- ADSP
- CDSP

This will take some time and effort.  Oh, and I'd like to make the NXPs operational, too. :grinning: Luckily, for Volterra you can do without all these and still have a useful VM platform with working thermal management. So, not everything is bad.
