### ISSUE TITLE
Help wanted not same device related 

### ISSUE THREAD

**Issue by Saikatsaha1996** [jglathe/linux_ms_dev_kit#22]
Hi ! 
I am Saikat Saha I am porting my downstream device to mainline.. I am facing some issues.. which you faced already.. 
My issue 

```
[    1.151192] dwc3 a600000.usb: Adding to iommu group 8
[    1.207374] qcom_pmic_glink pmic-glink: Failed to create device link (0x180) with a600000.usb
[    2.611013] synth uevent: /devices/platform/pmic-glink/pmic_glink.power-supply.0/power_supply/qcom-battmgr-bat: failed to send uevent
[    2.611228] power_supply qcom-battmgr-bat: uevent: failed to send synthetic uevent: -11
[    2.611328] synth uevent: /devices/platform/pmic-glink/pmic_glink.power-supply.0/power_supply/qcom-battmgr-usb: failed to send uevent
[    2.611347] power_supply qcom-battmgr-usb: uevent: failed to send synthetic uevent: -11
[    2.611410] synth uevent: /devices/platform/pmic-glink/pmic_glink.power-supply.0/power_supply/qcom-battmgr-wls: failed to send uevent
[    2.611428] power_supply qcom-battmgr-wls: uevent: failed to send synthetic uevent: -11
[    2.729598] qcom_pmic_glink pmic-glink: Failed to create device link (0x180) with 0-0042
```
I want to know how you fix it ? Please share some suggestions if possible..

**Comment by jglathe** [comment]
Hi! Well those pmic-glink errors are quite persistent and I have no idea how to fix them. 

![image](https://github.com/user-attachments/assets/791bd07f-0462-4787-88eb-0d0c5d34e559)

![image](https://github.com/user-attachments/assets/df28aa97-7cb7-496a-9f24-2c37eda7477a)

On the WDK it doesn't really affect anything (that I notice). On the HP Omnibook X14 (x1e laptop) I get exactly the same errors, but battery life is good and suspend / resume works. :man_shrugging:

**Comment by Saikatsaha1996** [comment]
> Hi! Well those pmic-glink errors are quite persistent and I have no idea how to fix them.
> 
> ![image](https://private-user-images.githubusercontent.com/33185912/378118937-791bd07f-0462-4787-88eb-0d0c5d34e559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjk0MDgsIm5iZiI6MTcyOTM2OTEwOCwicGF0aCI6Ii8zMzE4NTkxMi8zNzgxMTg5MzctNzkxYmQwN2YtMDQ2Mi00Nzg3LTg4ZWItMGQwYzVkMzRlNTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIwMTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZDE1YzEwYmI1NGY5ZDEyZWY4Nzg0ZDdiZjViNTFiM2YwYmY5NmU3MzI1OTZlYmY1ZWNlZjkzZGQxNDdiYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7aALpzUB-MzwDKOn629DvtQCTtXwwLp8SM2nFw43YqI)
> 
> ![image](https://private-user-images.githubusercontent.com/33185912/378118975-df28aa97-7cb7-496a-9f24-2c37eda7477a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjk0MDgsIm5iZiI6MTcyOTM2OTEwOCwicGF0aCI6Ii8zMzE4NTkxMi8zNzgxMTg5NzUtZGYyOGFhOTctN2NiNy00OTZhLTlmMjQtMmMzN2VkYTc0NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIwMTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZmQ5MTUyN2IxZjg4ZTA4OTFhNWM0MDEzOTViMWJlNmRmYmFlZmI2ZjE1NGI2M2YxZjU4NjQyNWE4OWI1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ou3NFtmT7HYEZzMLjuAkyYlSYHylYIfmxzs7mKjwJ_Y)
> 
> On the WDK it doesn't really affect anything (that I notice). On the HP Omnibook X14 (x1e laptop) I get exactly the same errors, but battery life is good and suspend / resume works. 🤷‍♂️

Thank you so much for your response..

I actually have charging issue for my device.. so it can be reason for charging?

Even my device battery status also red & reporting unknown 
![IMG_20241018_113346](https://github.com/user-attachments/assets/e96b89a5-427c-4e86-8a50-e2c947968977)

**Comment by jglathe** [comment]
This is something else. Looks like the adsp firmware is not loaded.

**Comment by Saikatsaha1996** [comment]
> This is something else. Looks like the adsp firmware is not loaded.

Adsp loaded and booted up successfully 
[armbian3.txt](https://github.com/user-attachments/files/17447304/armbian3.txt)
```
[    5.231943] remoteproc remoteproc2: powering up 17300000.remoteproc
[    5.231951] remoteproc remoteproc2: Booting fw image qcom/sm8350/realme/porsche/adsp.mbn, size 17078428
[    5.516803] remoteproc remoteproc2: remote processor 17300000.remoteproc is now up
```

**Comment by jglathe** [comment]
hmm do you have the pd-mapper on in the kernel , or do you use pd-mapper and qrtr as user mode processes? Also, if there are defining jsn files, are they available (at the same place as the firmware) and loaded?

**Comment by Saikatsaha1996** [comment]
> hmm do you have the pd-mapper on in the kernel , or do you use pd-mapper and qrtr as user mode processes? Also, if there are defining jsn files, are they available (at the same place as the firmware) and loaded?

Yea.. pd-mapper available..
https://github.com/Saikatsaha1996/build/blob/a4621a4808ff53b0104bee2ec3206dc4fcbcc415/config/boards/xiaomi-elish.conf#L76

And jsn file also available all firmwares
https://github.com/Saikatsaha1996/firmware/tree/porsche/qcom/sm8350/realme/porsche

**Comment by Saikatsaha1996** [comment]
> hmm do you have the pd-mapper on in the kernel , or do you use pd-mapper and qrtr as user mode processes? Also, if there are defining jsn files, are they available (at the same place as the firmware) and loaded?

Okay most probably charger_pd adsp.jsn file is missing?
https://github.com/Saikatsaha1996/android_kernel_oneplus_sm8350/blob/9c86b0cf0172c8ca42ed377af48c0e877ba7a050/arch/arm64/boot/dts/vendor/qcom/lahaina.dtsi#L5591

**Comment by Saikatsaha1996** [comment]
> hmm do you have the pd-mapper on in the kernel , or do you use pd-mapper and qrtr as user mode processes? Also, if there are defining jsn files, are they available (at the same place as the firmware) and loaded?

Okay got it this one right?
https://github.com/Saikatsaha1996/firmware-realme-porsche/blob/porsche/lib/firmware/qcom/sm8350/porsche/battmgr.jsn

**Comment by Saikatsaha1996** [comment]
Finally qcom battmgr working.. with `battmgr.jsn` but still device not charging..
![IMG_20241020_071657](https://github.com/user-attachments/assets/b0407620-32cc-4917-9937-1564ccd776a9)

**Comment by jglathe** [comment]
are there other .jsn files? I don't know enough to assist in debugging it deeper.

**Comment by Saikatsaha1996** [comment]
> are there other .jsn files? I don't know enough to assist in debugging it deeper.

But magically you give me a strong clues for fix my battery manager.. thank you so much 😁..

This is my total full firmwares.. no more jsn file available
https://github.com/Saikatsaha1996/firmware-realme-porsche/tree/porsche/lib/firmware/qcom/sm8350/porsche

Still my device not charging.. only battery status reporting currect..
![IMG_20241020_170117](https://github.com/user-attachments/assets/3d13c6c3-9534-48d3-8396-c53be2b53bbb)

**Comment by jglathe** [comment]
Hmm looks to me that there are other .jsn files (like adspr.jsn). For sc8280xp it is usually four files, but yours is sm8350:

![image](https://github.com/user-attachments/assets/70339407-f11b-44e2-bc13-3202811ec102)

Those 4 files are in the firmware directory, too. :man_shrugging: I would recommend to have them in the initramfs, like [here](https://github.com/jglathe/wdk2023_syshacks/blob/jg/hp-omnibook-x14/etc/initramfs-tools/hooks/x14-firmware) example only, need to do this with your paths and firmwares). What I can tell (from binwalking UEFI updates) is that it appears to be usually these 4 .jsn files you need.

**Comment by Saikatsaha1996** [comment]
> Hmm looks to me that there are other .jsn files (like adspr.jsn). For sc8280xp it is usually four files, but yours is sm8350:
> 
> ![image](https://private-user-images.githubusercontent.com/33185912/378190062-70339407-f11b-44e2-bc13-3202811ec102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Njg0MzksIm5iZiI6MTcyOTQ2ODEzOSwicGF0aCI6Ii8zMzE4NTkxMi8zNzgxOTAwNjItNzAzMzk0MDctZjExYi00NGUyLWJjMTMtMzIwMjgxMWVjMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDIzNDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmFlM2YwMTA4YzIyNGNjNjM1MjgyOTZkZDE5MWM2OGJlNzlkZTY0OWY1MGU2NmNmZjRiYWIwZDk5YWJhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vKB7b4kt3lkSQ7LSLUX0cMGEIhpEYZmlNL5ERcfDGtg)
> 
> Those 4 files are in the firmware directory, too. 🤷‍♂️ I would recommend to have them in the initramfs, like [here](https://github.com/jglathe/wdk2023_syshacks/blob/jg/hp-omnibook-x14/etc/initramfs-tools/hooks/x14-firmware) example only, need to do this with your paths and firmwares). What I can tell (from binwalking UEFI updates) is that it appears to be usually these 4 .jsn files you need.

I already all does have.. like

```
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/adspr.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/adspua.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/battmgr.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/cdspr.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/modemr.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/slpir.jsn
https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/slpius.jsn
```

**Comment by Saikatsaha1996** [comment]
> > Hmm looks to me that there are other .jsn files (like adspr.jsn). For sc8280xp it is usually four files, but yours is sm8350:
> > ![image](https://private-user-images.githubusercontent.com/33185912/378190062-70339407-f11b-44e2-bc13-3202811ec102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Njg0MzksIm5iZiI6MTcyOTQ2ODEzOSwicGF0aCI6Ii8zMzE4NTkxMi8zNzgxOTAwNjItNzAzMzk0MDctZjExYi00NGUyLWJjMTMtMzIwMjgxMWVjMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDIzNDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MmFlM2YwMTA4YzIyNGNjNjM1MjgyOTZkZDE5MWM2OGJlNzlkZTY0OWY1MGU2NmNmZjRiYWIwZDk5YWJhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vKB7b4kt3lkSQ7LSLUX0cMGEIhpEYZmlNL5ERcfDGtg)
> > Those 4 files are in the firmware directory, too. 🤷‍♂️ I would recommend to have them in the initramfs, like [here](https://github.com/jglathe/wdk2023_syshacks/blob/jg/hp-omnibook-x14/etc/initramfs-tools/hooks/x14-firmware) example only, need to do this with your paths and firmwares). What I can tell (from binwalking UEFI updates) is that it appears to be usually these 4 .jsn files you need.
> 
> I already all does have.. like
> 
> ```
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/adspr.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/adspua.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/battmgr.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/cdspr.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/modemr.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/slpir.jsn
> https://github.com/Saikatsaha1996/firmware/blob/porsche/qcom/sm8350/realme/porsche/slpius.jsn
> ```

Finally solved my device charging issue.. now device charging at full speed.. but still one issue present.. like battery charging indicator not showing.. only battery persentage increased & dmesg outputs..
![IMG_20241022_000630](https://github.com/user-attachments/assets/dc3c8858-3b52-4cb5-8efd-01fa4a4e1261)
![IMG_20241022_000601](https://github.com/user-attachments/assets/aee0729d-5200-4924-bc2a-439e734404ec)

**Comment by jglathe** [comment]
That is way more talkative than the X13s :laughing:  Honestly, no idea.
